package com.example.domain.attention

/**
 * The three raw signal components before weighting.
 *
 * Each component is in [0, 1] except [datePressure] which can reach [AttentionCalculator.MAX_PRESSURE]
 * for overdue tasks. The final [AttentionResult.score] is clamped to [0, 1].
 */
data class AttentionComponents(
    /** Logistic pressure from deadline proximity. 0 = far away, 1 = at deadline, >1 = overdue. */
    val datePressure: Float,
    /** Quadratic decay from last meaningful interaction. 0 = recently interacted, 1 = stale. */
    val staleness: Float,
    /** Diminishing-returns avoidance from reschedule count. 0 = never rescheduled, →1 = many. */
    val avoidance: Float
)

/**
 * A human-readable reason why this task demands attention.
 *
 * Generated by [AttentionCalculator] for tasks whose weighted signal contribution
 * exceeds [AttentionCalculator.REASON_THRESHOLD]. The UI formats these into
 * localized strings.
 */
sealed class AttentionReason {
    /** Task deadline is approaching (remaining days > 0). */
    data class NearDeadline(val remainingDays: Int) : AttentionReason()

    /** Task deadline has passed (overdue by [overdueDays]). */
    data class Overdue(val overdueDays: Int) : AttentionReason()

    /** No meaningful interaction for [daysSinceLastInteraction] days. */
    data class StaleInteraction(val daysSinceLastInteraction: Int) : AttentionReason()

    /** Task has been rescheduled [rescheduleCount] times. */
    data class Avoidance(val rescheduleCount: Int) : AttentionReason()
}

/**
 * The result of computing attention for a single task.
 *
 * @param score final attention score [0, 1]. Higher = closer to the Sun.
 * @param components raw signal values before weighting (for debugging / future tuning).
 * @param reasons non-empty list of human-readable reasons driving the score.
 */
data class AttentionResult(
    val score: Float,
    val components: AttentionComponents,
    val reasons: List<AttentionReason>
)
